# Parameters
LEARNING_RATE = 0.001
TRAINING_ITERS = 60000
DISPLAY_STEP = 1000
TIME_STEPS = 9
FINGER_SIZE = 5
N_HIDDEN = 256
BLOCK_LENGTH = 6
FUTURE_LENGTH = 2
BIRNN = True
CHECKPOINT_PATH = 'trained_models/cp.ckpt'
LOG_PATH = 'logs/'
