# Parameters
LEARNING_RATE = 0.001
TRAINING_ITERS = 60000
DISPLAY_STEP = 1000
TIME_STEPS = 9
FINGER_SIZE = 5
N_HIDDEN = 256
BIRNN = True
BLOCK_LENGTH = 12
FUTURE_LENGTH = 9
CHECKPOINT_PATH = 'trained_models/cp.ckpt'
LOG_PATH = 'logs/'
DATA_DIR = '../Datasets/JPDataset/'
HMM_RES_DIR = '../Datasets/JPResDataset/'
